feat: adds running yarn projen pre-push

diff --git a/.husky/pre-push b/.husky/pre-push
--- a/.husky/pre-push
+++ b/.husky/pre-push
@@ -1,3 +1,22 @@
 # ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".
 
-echo "make sure the project is not out of sync with .projenrc.ts"
+#!/bin/sh
+
+CYAN="\033[1;36m"
+RED="\033[1;31m"
+RESET="\033[0m"
+
+# Run projen
+echo "${CYAN}Verifying there are no uncommitted projen changes${RESET}"
+yarn projen
+
+# Check for git changes
+if git diff --quiet; then
+  echo "✅ No changes detected. Proceeding with commit."
+  exit 0
+else
+  echo "${RED}❌ ERROR: Running 'yarn projen' resulted in file changes.${RESET}"
+  echo "${RED}❌ Please commit these changes before proceeding.${RESET}"
+  exit 1
+fi
+
