refactor: changes to use projenrc folder (#92)

diff --git a/.husky/pre-push b/.husky/pre-push
--- a/.husky/pre-push
+++ b/.husky/pre-push
@@ -1,6 +1,8 @@
+#!/bin/sh
+
 # ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".
 
-#!/bin/sh
+set -e
 
 CYAN="\033[1;36m"
 RED="\033[1;31m"
@@ -9,14 +11,14 @@ RESET="\033[0m"
 
 # Run projen
 echo "${CYAN}Verifying there are no uncommitted projen changes${RESET}"
-yarn projen
+npx projen
 
 # Check for git changes
 if git diff --quiet; then
   echo "${GREEN}✅ No changes detected. Proceeding with commit.${RESET}"
   exit 0
 else
-  echo "${RED}❌ ERROR: Running 'yarn projen' resulted in file changes.${RESET}"
+  echo "${RED}❌ ERROR: Running 'npx projen' resulted in file changes.${RESET}"
   echo "${RED}❌ Please commit these changes before proceeding.${RESET}"
   exit 1
 fi
